import type { Metadata } from 'next'
import React from 'react'
import '@/shared/ui/styles/root_variables/index.css'
import '@/shared/ui/styles/index.scss'
import StoreProvider from '@/app/storeProvider'
import { PopUp } from '@/shared/ui/popUp/PopUp'
import s from '../src/app/layout.module.scss'
import { Header } from '@/widgets'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang={'en'}>
      <body>
        <StoreProvider>
          <div className={s.layoutContainer}>
            <Header />
            {children}
            <PopUp />
          </div>
        </StoreProvider>
      </body>
    </html>
  )
}
