import type { Metadata } from 'next'
import React from 'react'
import Link from 'next/link'
import '@/shared/ui/styles/root_variables/index.css'
import '@/shared/ui/styles/index.scss'
import {Header} from '@/widgets/header/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const pages = [
  'Auth/Sign-in',
  'Auth/Sign-up',
  'Create_Publication',
  'Favorites',
  'Feed',
  'Messenger',
  'Post',
  'Profile',
  'Profile_Settings',
  'Search',
  'Statistics',
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang={'en'}>
      <body>
      <Header newMessage={true}/>
        {/*<header style={{ display: 'flex', gap: '30px', padding: '30px' }}>*/}
        {/*  {pages.map(page => (*/}
        {/*    <Link key={page} href={`/${page.toLowerCase()}`}>*/}
        {/*      <h3>{page}</h3>*/}
        {/*    </Link>*/}
        {/*  ))}*/}
        {/*</header>*/}
        {children}
      </body>
    </html>
  )
}
