import type { Metadata } from 'next'
import React from 'react'
import '@/shared/ui/styles/root_variables/index.css'
import '@/shared/ui/styles/index.scss'
import { Providers } from '@/app/Providers'
import { Layout } from '@/app/Layout'

export const metadata: Metadata = {
  title: 'Inctagram',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang={'en'}>
      <body>
        <Providers>
          <Layout>{children}</Layout>
        </Providers>
      </body>
    </html>
  )
}
